apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: eu2scxx40-go 
  janus-idp.io/tekton: eu2scxx40-go
  backstage.io/kubernetes-id: eu2scxx40-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: eu2scxx40-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  